name: Set up Porfolio Integration runs
# This CI should run on every Pull request made  
on:
  push:
    branches: 
      - main
jobs: 
  sample-job:
    name: first job
    runs-on: ubuntu-latest
    steps: 
      - run: echo 'This is a hello world Test'
