name: Set up Porfolio Integration runs
# This CI should run on every Pull request made  
on:
  pull_request:
    types: [opened] 
    branches: 
      'dev/**'
jobs: 
  sample-job:
    name: Run CI on opned PR
    runs-on: ubuntu-latest
    steps: 
      - run: echo 'This is a hello world Test'
