name: Terraform set up for continuous deployment of AWS resource
run-name: ${{ github.actor }} has triggered the pipeline

on: workflow_dispatch

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECERET_ACCESS_KEY}}
  BUCKET_NAME: ${{vars.BUCKET_NAME}}
  DOMAIN_NAME: ${{vars.DOMAIN_NAME}}
  ZONE_ID: ${{vars.ZONE_ID}}

jobs:
  create_aws_infrastructure:
    name: terraform-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: Stephen8898/site-infrastructure
          path: site-infrastructure

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        id: init
        run: terraform init
        working-directory: ./site-infrastructure

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./site-infrastructure

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="bucket_name=${{vars.BUCKET_NAME}}" -var="domain_name=${{vars.DOMAIN_NAME}}" -var="zone_id=${{vars.ZONE_ID}}" -out=tfplan -input=false -no-color
        working-directory: ./site-infrastructure
      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false tfplan
        working-directory: ./site-infrastructure

  uploud_to_bucket:
    needs: create_aws_infrastructure
    name: deploy_files_to_s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECERET_ACCESS_KEY}}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1

      - name: Upload files to S3 bucket
        run: |
          aws s3 cp ./stephen-portfolioV2/index.html s3://${{vars.BUCKET_NAME}}/ 
          aws s3 cp ./stephen-portfolioV2/error.html s3://${{vars.BUCKET_NAME}}/ 
          aws s3 cp ./stephen-portfolioV2/error.css s3://${{vars.BUCKET_NAME}}/
          aws s3 cp ./stephen-portfolioV2/styles.css s3://${{vars.BUCKET_NAME}}/
          aws s3 cp ./stephen-portfolioV2/scripts.js s3://${{vars.BUCKET_NAME}}/
        shell: bash
