name: Terraform set up for continuous deployment of AWS resource
run-name: ${{ github.actor }} has triggered the pipeline

on: workflow_dispatch

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECERET_ACCESS_KEY}}
  CERTIFICATE_ARN: ${{vars.CERTIFICATE_ARN}}
  SUB_DOMAIN_NAME: ${{ vars.SUB_DOMAIN_NAME}}
  DOMAIN_NAME: ${{vars.DOMAIN_NAME}}
  ZONE_ID: ${{vars.ZONE_ID}}

jobs:
  create_aws_infrastructure:
    name: terraform-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: Stephen8898/site-infrastructure
          path: site-infrastructure

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        id: init
        run: terraform init
        working-directory: ./site-infrastructure

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./site-infrastructure

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="bucket_name=${{vars.DOMAIN_NAME}}" \
          -var="domain_name=${{vars.SUB_DOMAIN_NAME}}" \
          -var="zone_id=${{vars.ZONE_ID}}" \
          -var="certificate_arn=${{vars.CERTIFICATE_ARN}}"
          -input=false -no-color
        working-directory: ./site-infrastructure
      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false
        working-directory: ./site-infrastructure
