name: Terraform set up for continuous deployment of AWS resource
run-name: ${{ github.actor }} has triggered the pipeline

on: workflow_dispatch

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECERET_ACCESS_KEY}}

jobs:
  create_aws_infrastructure:
    name: terraform-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: Stephen8898/site-infrastructure
          path: site-infrastructure

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        id: init
        run: terraform init
        working-directory: ./site-infrastructure

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./site-infrastructure

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./site-infrastructure

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./site-infrastructure

  uploud_to_bucket:
    name: deploy_files_to_s3
    runs-on: ubuntu-latest
    steps:
      - run: ""
