name: Uploud files to S3 bucket
run-name: ${{ github.actor }} has triggered the pipeline

on: workflow_dispatch

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECERET_ACCESS_KEY}}
  BUCKET_NAME: ${{vars.BUCKET_NAME}}

jobs:
  uploud_to_bucket:
    name: deploy_files_to_s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECERET_ACCESS_KEY}}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
      - name: Upload files to S3 bucket
        run: aws s3 ls
        #   aws s3 cp ../stephen-portfolioV2/index.html s3://${{vars.BUCKET_NAME}}/
        #   aws s3 cp ../stephen-portfolioV2/error.html s3://${{vars.BUCKET_NAME}}/
        #   aws s3 cp ../stephen-portfolioV2/error.css s3://${{vars.BUCKET_NAME}}/
        #   aws s3 cp ../stephen-portfolioV2/styles.css s3://${{vars.BUCKET_NAME}}/
        #   aws s3 cp ../stephen-portfolioV2/scripts.js s3://${{vars.BUCKET_NAME}}/
        shell: bash
