name: Uploud files to S3 bucket
run-name: ${{ github.actor }} has triggered the pipeline

on: workflow_dispatch

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECERET_ACCESS_KEY}}
  DOMAIN_NAME: ${{vars.DOMAIN_NAME}} #Name of the S3 bucket

jobs:
  uploud_to_bucket:
    name: deploy_files_to_s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: push objects to bucket
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./stephens-portfolioV2/
          destination: s3://${{vars.DOMAIN_NAME}}/
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_access_key: ${{secrets.AWS_SECERET_ACCESS_KEY}}
          aws_region: us-east-1
          flags: --recursive
